version: '3'

services:
  dropbox-backup:
    build: .
    container_name: dropbox-backup
    restart: always
    environment:
      DEBUG_LEVEL: WARNING
    volumes:
      - ./backup-docker/temp:/app/temp
      - ${WATCH_FOLDER}:/backup
